### ISSUE TITLE
带空格的本地目录/网盘目录场景下有问题

### ISSUE THREAD

**Issue by bluer007** [masx200/baidupcs-batch-upload#1]
我也有这种批量上传的需求, 好久之前找过https://github.com/iikira/BaiduPCS-Go   这个项目提issue, 不过他们没支持. 
所以想着自己写一个, 没想到楼主已经有现成的了, 很感谢. 
不过在测试过程中发现, 楼主的工具有点问题, 不支持带空格的目录场景, 例如运行: 
npx @masx200/baidupcs-batch-upload --input="I:\2        2" --dest="/test/t         s" --concurrent=20

会提示找不到本地文件, 并且如果网盘目录中带空格, 也是有问题的, 上传到其他目录去了.  
希望楼主可以修复下哈..我关注着咧
还有最好楼主上传下BaiduPCS-Go.exe的压缩包到项目中呗, 因为我发现原来的项目已经被百度叫去喝茶了, 已经全网封禁了, 多可惜啊 .

**Comment by masx200** [comment]
BaiduPCS-Go-v3.6.2-windows-x64 

https://share.weiyun.com/4ZFFhW4E

**Comment by masx200** [comment]
发现是npx的问题,直接运行它就没问题了
```
 baidupcs-batch-upload.cmd --input="d:\2 2" --dest="/test/t s" --concurrent=20
```
