### ISSUE TITLE
我是不是方法不对？上传速度只有100K

### ISSUE THREAD

**Issue by hoa1999** [masx200/baidupcs-batch-upload#4]
我是SVIP  我用百度的客户端下载速度有5M  上传也有1M  

但是用了这个
https://github.com/masx200/baidupcs-batch-upload/releases/download/1.1.5/BaiduPCS-Go-v3.6.2-windows-x64.zip

下载和上传都稳定到100K.。。需要哪里设置吗？

我直接下载然后运行的。登录账号。。。

**Comment by masx200** [comment]
这个，会员对它无效吧

**Comment by masx200** [comment]
有会员自然是不需要它了

**Comment by masx200** [comment]
这个恐怕只有Baidupcs-go的原作者才知道为什么了
