### ISSUE TITLE
请教一下安装使用问题

### ISSUE THREAD

**Issue by zzzop** [masx200/baidupcs-batch-upload#5]
`npm i -g @masx200/baidupcs-batch-upload`
执行后就是安装完成了吗
我运行
`npx @masx200/baidupcs-batch-upload  --input=/mnt/sda1/enc91/91all --dest=/91all`
显示错误是什么问题

> (node:12069) ExperimentalWarning: The ESM module loader is experimental.
> file:///usr/lib/node_modules/@masx200/baidupcs-batch-upload/node_modules/@masx200/mini-cli-args-parser/lib/parseargs.js:10
>             const groups = execArray?.groups;
>                                      ^
> 
> SyntaxError: Unexpected token '.'
>     at Loader.moduleStrategy (internal/modules/esm/translators.js:122:18)
>

**Comment by masx200** [comment]
那可以升级一下nodejs的版本了

**Comment by zzzop** [comment]
> 那可以升级一下nodejs的版本了

了解了，谢谢，遗憾版本升级不了了
